/** 总账业务错误：携带机器可读 code，便于调用方区分拒绝原因。 */
export class LedgerError extends Error {
  constructor(code, message, details = undefined) {
    super(message);
    this.name = "LedgerError";
    this.code = code;
    this.details = details;
  }
}

export const ErrorCodes = Object.freeze({
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DUPLICATE_EVENT: "DUPLICATE_EVENT",
  STREAM_VERSION_CONFLICT: "STREAM_VERSION_CONFLICT",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  UNKNOWN_EVENT: "UNKNOWN_EVENT",
  UNKNOWN_ASSET: "UNKNOWN_ASSET",
  UNKNOWN_SHOT: "UNKNOWN_SHOT",
  UNKNOWN_SCOPE: "UNKNOWN_SCOPE",
  REJECTED_ANCESTOR: "REJECTED_ANCESTOR",
  REJECTED_SHOT_REUSED: "REJECTED_SHOT_REUSED",
  BASELINE_NOT_LOCKED: "BASELINE_NOT_LOCKED",
  BASELINE_DRIFT: "BASELINE_DRIFT",
  BASELINE_LOCKED: "BASELINE_LOCKED",
  SCOPE_NOT_FROZEN: "SCOPE_NOT_FROZEN",
  ALREADY_DECIDED: "ALREADY_DECIDED",
  NOT_SIGNED: "NOT_SIGNED",
  SIGNER_UNAUTHORIZED: "SIGNER_UNAUTHORIZED",
  REVIEW_PATH_MISMATCH: "REVIEW_PATH_MISMATCH",
  REASSESSMENT_NOT_TRIGGERED: "REASSESSMENT_NOT_TRIGGERED",
  MASTER_NOT_RELEASED: "MASTER_NOT_RELEASED",
  MASTER_MISMATCH: "MASTER_MISMATCH",
  PACKAGE_PUBLISHED: "PACKAGE_PUBLISHED",
  ASSET_NOT_IN_CUT: "ASSET_NOT_IN_CUT",
  SENSITIVE_ASSET: "SENSITIVE_ASSET",
  RECEIVER_UNKNOWN: "RECEIVER_UNKNOWN",
});
